server:
  port: 8010
spring:
  application:
    name: order
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 888Chinapnr123
#    url: jdbc:mysql://115.159.41.44:3306/seata?characterEncoding=utf-8

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: OBTM_HD
    password: hd1234!
    url: jdbc:oracle:thin:@//31.2.8.203:1521/OBTMHD