spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: alibaba-cloud-provder
          uri: lb://alibaba-cloud-provder
          predicates:
            - Path=/provder/**
        - id: alibaba-cloud-member
          uri: lb://alibaba-cloud-member
          predicates:
            - Path=/member/**

