server:
  port: 8020
spring:
  application:
    name: pay
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 888Chinapnr123
    url: jdbc:mysql://115.159.41.44:3306/seata-product?characterEncoding=utf-8
